### PR TITLE
Development

### PR DESCRIPTION
**Pull request by rsinger86**

### CODE REVIEW

**Comment by rsinger86** [comment]
@ADR-007, what is the purpose of `required_query_fields` in the filter backend class you wrote?

**Comment by ADR-007** [comment]
Probably it would be better to rename `required_query_fields` to `always_included_fields`

It is useful when you have properties based on some fields.

But maybe some kind of rules should be added in the future like: `{'my_propery': ['used_field1']} `

**Comment by rsinger86** [comment]
Ah, so if you have a computed serializer field that relies on one or more model fields? And this is part of the public API?

**Comment by ADR-007** [comment]
Exactly

**Comment by rsinger86** [comment]
Okay, cool. This feature/filtering backend is in the latest release. The `required_query_fields` option is not documented, though, so feel free to consider alternatives and submit another pull request that modifies the parameter's API :)

**Pull request merged**
